### ISSUE TITLE
We need to change the access to dev mode

### ISSUE THREAD

**Issue by newchild** [eddy5641/LegendaryClient#144]
Leaks are spreading everywhere. I would request to move it to a different location and change the way we currently access devmode

**Comment by Dispersia** [comment]
the entire source is online, and devmode isn't what actually is causing the problem and no matter where we move it it's a single line to break everything :P, there isn't much you can do about it, it took me 5 minutes to write it for the official client anyway, it's the concept that needs fixed on their end, not the implementation.

 I mean I get what you mean with it being spread, but it's not like it's a hard idea, no matter what we do to it they could just readd the line and spread it again >.<

**Comment by newchild** [comment]
Well I guess you are right. What we could do is changing "the key" every now and then so it isn't as easy as it is currently to leak features that are pretty gamebreaking :/ Issue can be closed as soon as you answer I guess.
Edit:
Also you might saw the post on epvpers where a preson tried to sell access to devmode. This is what I am currently most worried about.

**Comment by Dispersia** [comment]
I have seen a few people do it, I always post when I see it to call them out and hopefully bring awareness to people. Someone went through the boosting companies and tried to sell it to them too, which is a legitimate concern. Eventually devmode will be global and a property instead of chat command, which I will probably fix very soon (as it's meant for developers, not users), but even then, it would be pretty easy to get to unfortunately

**Comment by eddy5641** [comment]
Solution, Require a key that can be changed from the website.
