### ISSUE TITLE
Currently Known Bugs [INPROGRESS]

### ISSUE THREAD

**Issue by JamaicanMoose** [eddy5641/LegendaryClient#20]
GENERAL
- trying to enter champion select crashes the game {PATCHED}
- friends cant be added {UNFINISHED}
- EU West is not functioning {UNFINISHED} https://github.com/eddy5641/LegendaryClient/issues/8
- asdf

CUSTOM GAME
- bots can't be added {UNFINISHED} https://github.com/eddy5641/LegendaryClient/issues/17
- asdf

**Comment by eddy5641** [comment]
[Is in dev?]{Priority Currently}
Trying to enter champion select crashes the game [FIXED]{null}
Trying to enter champion select crashes the because of new trading features [FIXED]{null}
[NEW]: Can not search for champs {5}
Patcher Can not update Game Client [In Dev]{1}
Bots can't be added[In Dev]{2}
Invites not working [In Dev] {3}
Friends can't be added [In Dev]{3}
Trading not working [FIXED] {null}
Can not switch to spectator [In Dev]{4}
Other Regions _EU West LA South_[In Dev]{4}
Custom Games sometimes start multiple clients (uses league of legends game client){Last}

|Add Me On Skype: ed vo / eddydavinchi | Add Me On League [NA ONLY]: eddy5641 |
Updated for next patch 1.0.1.0 [legendaryclient]

**Comment by GodLesZ** [comment]
Single issues would be better IMHO.
This can't be up-to-date and also isn't the best workflow for bug and development tracking ;)

**Comment by eddy5641** [comment]
I was thinking the same thing, especially because this isn't being updated anymore.
