### ISSUE TITLE
legendary client has stop working while "patching"

### ISSUE THREAD

**Issue by maxiking913** [eddy5641/LegendaryClient#75]

**Comment by maxiking913** [comment]
Its simple crash when it want to update

**Comment by maxiking913** [comment]
compiled myself and tried newest realease

**Comment by nairaner** [comment]
riot updated release list but not release manifest, just wait until next patch is released

**Comment by Dispersia** [comment]
As nairaner said, if you check http://l3cdn.riotgames.com/releases/live/projects/lol_air_client/releases/releaselisting they said we're on 0.0.1.113, when we are on 0.0.1.112. A temp fix is on PatcherPage.xaml.cs, go to string LatestVersion and get [1] instead of [0]. (113 is for next patch which comes out later today)
